Add an endgame recipe for the creative tablet
GTNewHorizons/Botanic-horizons pull request #11
Opened 2022-06-12 09:06 UTC by combusterf

Adds a creative tablet due to demand. It uses the already available creative pool as a dependency, so no new shortcuts are added.

2022-06-12 12:05 UTC, Connor-Colenso submitted a review, later dismissed
It's too early to be doing stuff like this imo, giving out creative items pre-emptively for a mod we haven't finished balancing is a bad idea.

2022-06-12 12:28 UTC, boubou19 commented
infinity plates in addition of the creative pool isn't going to cause any issue as you have to beat the game to craft that.

2022-07-11 04:07 UTC, Connor-Colenso requested changes, later dismissed
Firstly this is an inappropriate recipe regardless, basic 3x3 crafting for a creative item? Really?

Secondly outvoted by who? Don't see anyone rushing to approve this.

2022-07-11 04:16 UTC, mitchej123 commented
Let's not add creative items until everything else is balanced...

2022-07-11 07:03 UTC, Sphyix commented
I don't see how requesting an infinity plate can cause issues tbh.
It can be balanced better, sure, but not adding it is probably worse.

2022-07-11 07:11 UTC, boubou19 commented
i understand the concerns of the others about adding creative items before the balance is settled. I don't count the times where a super OP item was craftable with endgame stuff of the moment just to see its recipe reworked monthes or years later because we pushed back the endgame or because someone added a new way to produce resources making the item dirt cheap to make.

The real question is: do we really plan to add later new botania content post infinity? Botania seems to be already spread out to a maximum.

2022-07-27 17:09 UTC, combusterf commented
I present this as further evidence that Colen has a bad habit of autocratically killing progress when they disagree and not answering to queries or requests of fellow admins.

2022-08-05 21:08 UTC, Connor-Colenso commented
Thank you for your opinion, it will be noted and we will look through it carefully.

2022-08-05 21:16 UTC, Connor-Colenso commented
I apologise for prematurely closing this, after discussion on discord it seems that you did indeed follow up with a better alternative. Please post a clear picture though so it's easier for us to evaluate. Thanks.

2022-08-05 21:20 UTC, combusterf commented
![image](https://user-images.githubusercontent.com/8459776/183202192-073362f8-667f-4fcf-9e25-6cd5029fd173.png)
![image](https://user-images.githubusercontent.com/8459776/183202350-c1c75e31-530b-49e7-a232-2e909155e881.png)

2022-08-05 21:26 UTC, boubou19 approved these changes

2022-08-05 21:26 UTC, merged