Update AvaritiaPatches.java
GTNewHorizons/Botanic-horizons pull request #22
Opened 2023-06-15 15:28 UTC by EnderProyects

add recipe for the creative flower using all mana flowers

2023-06-15 20:11 UTC, combusterf requested changes
- There already exists a recipe for the Asgardandelion
- This new recipe is an order of magnitude more expensive than the ones for the creative pool and creative tablet, despite having equivalent functionality

2023-06-15 21:08 UTC, EnderProyects commented
I make the pr because I have it in my computer for some months for now, also I make it for two reasons:
- With this recipe people NEED to make at least something of botania in order to get the flower, in the normal recipe you get free mana for nothing of content of botania
- For me it was like giving people infinite amount of essentia without using thaumcraft
P.s I can change the infinite plates amount needed for the recipe if you like it

2023-06-15 21:24 UTC, EnderProyects commented
Also in terms of costs the original recipe is already expensive about inf ingots ( but without any botania cost)
![image](https://github.com/GTNewHorizons/Botanic-horizons/assets/45178400/3b207bd4-cde0-4aaa-a377-eef59042f4e3)

2023-06-15 21:26 UTC, EnderProyects commented
And here you have the one I propossed months ago it uses a litle bit more of ingots in plate form, and all the mana producer flowers:
![image](https://github.com/GTNewHorizons/Botanic-horizons/assets/45178400/2b584391-54e7-4a99-a9c4-a56d3a97ca90)

2023-06-16 18:11 UTC, combusterf requested changes
Argument ad nauseam. Previous points were NOT addressed.

2023-06-16 18:23 UTC, combusterf commented
- Infinity is still expensive, using dense plates over single ingots is just bullying the user and an abuse of server resources. 
- Once you hit late UHV+ and get infinity you are entitled to braindead solutions. Your average player gets into Botania 10 tiers earlier than when they can make the infinity stuff.
- Adding every flower is also just about bullying the user into useless specific crafting effort rather than testing that they have infrastructure.
- The previous consensus in Discord was to not include stuff outside of botania - looking specifically at that thaintthistle that requires a bunch of thaumcraft nuisance.

2023-06-16 19:12 UTC, EnderProyects commented
![image](https://github.com/GTNewHorizons/Botanic-horizons/assets/45178400/f8df3c9e-9181-418a-a5bd-2f8509480290)
The thaintthistle is an eassy recipe, I dont see where is the problem, I can substitute it with the Gourmaryllis ( that I didnt include because is used in the craft of the Soarleander)
Also what about substituing the central dense plates with various plates of the mod itself? 
![image](https://github.com/GTNewHorizons/Botanic-horizons/assets/45178400/6a0ebc28-10b0-4f93-baf6-53043993fee3)

2023-06-18 13:30 UTC, Dream-Master commented
@EnderProyects any news ?

2023-06-18 13:52 UTC, EnderProyects commented
I'm at work, I will pr this later

2023-06-19 16:32 UTC, EnderProyects commented
I have messed something up in the recipe

2023-06-19 18:04 UTC, EnderProyects commented
I still have an issue, that I dont know what is happening, since all seems correct:
This turn into fire, instead of the infinitato
'Z', new ItemStack(LudicrousBlocks.infinitato),

2023-06-19 19:05 UTC, Dream-Master requested changes

2023-06-19 19:05 UTC, Dream-Master commented on src/main/java/net/fuzzycraft/botanichorizons/patches/AvaritiaPatches.java
> +                //'Z', new ItemStack(LudicrousBlocks.infinitato), // Until is fixed
fix it first. No duct tape recipes

2023-07-03 16:29 UTC, Dream-Master commented
@EnderProyects any news here ?

2023-07-03 16:32 UTC, EnderProyects commented
I tried many things and asked to people where the error is and haven't find a solution, so ATM the current recipe ( of the last pr) is what I would like to pr

2023-07-03 16:52 UTC, Dream-Master commented
i set it draft until it is fixed

2024-03-10 22:02 UTC, closed without merging